#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Mihir Shah

import readline
import sys
import time
import socket
import os
import colorama
import subprocess
import textwrap
import threading
import json

from shell.wrapper import TrainingWheelsWrapperClass

from colors.colors import *

if ( __name__ == "__main__" ):

	TrainingWheels = TrainingWheelsWrapperClass()

	TrainingWheels.run()
	'''
	# This invokes the Training Wheels shell, which kickstarts the
	# lessons and all the other interactions with the program.
	'''
